import 'tailwindcss/dist/tailwind.min.css'
import './styles/main.css'

// export { default as Alert } from './components/Alert'
// export { default as Breadcrumbs } from './components/Breadcrumbs'
export { Button } from './components/Button.jsx'
// export { default as Card } from './components/Card'
// export { default as Dropdown } from './components/Dropdown'
// export { default as Loader } from './components/Loader'
// export { default as Modal } from './components/Modal'
// export { default as Navbar } from './components/Navbar'
// export { default as Panel } from './components/Panel'
// export { default as Select } from './components/Select'
// export { default as Table } from './components/Table'
// export { default as Tabs } from './components/Tabs'
// export { default as Text } from './components/Text'
// export { default as TextArea } from './components/TextArea'
// export { default as TextField } from './components/TextField'
